[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
build-mode = "both"
excluded-patches = "'Disable typing indicator'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
rv-brand = "YT-Advanced ReVanced"
build-mode = "both"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
build-mode = "both"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
rv-brand = "YT-Advanced ReVanced"
build-mode = "both"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
rv-brand = "YT-Advanced ReVanced"
build-mode = "both"

[Tiktok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
build-mode = "both"

[com.facebook.katana]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/facebook"
build-mode = "both"

[com.microblink.photomath]
apkmonk-dlurl = "https://www.apkmonk.com/app/com.microblink.photomath/"
build-mode = "both"
