enable-magisk-update = false

[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"
excluded-patches = "'Disable typing indicator'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
rv-brand = "YT-Advanced ReVanced"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
rv-brand = "YT-Advanced ReVanced"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
rv-brand = "YT-Advanced ReVanced"

[com.facebook.katana]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/facebook"
arch = "arm64-v8a"
apkmirror-dpi = "360-640dpi"

[com.microblink.photomath]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photomath/"
